/* SPDX-License-Identifier: GPL-3.0-only */
/* The demo device of SLOOP live (web/live/mock.js) answers with the firmware's own tables: this prints them
 * as web/live/mockdata.js (engines with their edit parameters, page titles and preset names; the track and
 * global parameter descriptors; the drum kits).
 *   cc -O1 -w -Ibuild/gen -Ifirmware/src -Ifirmware/hal -o build/host/live_mockdata tests/live_mockdata.c -lm
 *   build/host/live_mockdata > web/live/mockdata.js */
#define main hostsim_main
#include "hostsim.c"
#undef main

static void js_str(const char *s)
{
    putchar('"');
    for (; s && *s; s++)
        if (*s == '"' || *s == '\\') printf("\\%c", *s); else putchar(*s);
    putchar('"');
}
static void js_desc(const param_desc_t *d)
{
    int32_t i;
    printf("[");
    js_str(d->label);
    printf(",%u,%d,%d,%d,", d->fmt, d->min, d->max, d->def);
    js_str(d->unit ? d->unit : "");
    if (d->fmt == F_ENUM && d->names) {
        printf(",[");
        for (i = 0; i <= d->max - d->min && i < 64; i++) {
            if (i) putchar(',');
            js_str(d->names[i]);
        }
        printf("]");
    }
    printf("]");
}

int main(void)
{
    uint32_t e, i;
    printf("// SPDX-License-Identifier: GPL-3.0-only\n// Generated by tests/live_mockdata.c from the firmware's tables: do not edit.\n");
    printf("// desc: [label, fmt, min, max, def, unit, names?]\nexport const MOCK = {\n  version: ");
    js_str("SLOOP 2.5 demo");
    printf(",\n  pCount: %u, gCount: %u, pE0: %u, nStep: %u,\n  engines: [\n", P_COUNT, G_COUNT, P_E0, NSTEP);
    for (e = 0; e < NENGINES; e++) {
        const engine_t *en = ENGINES[e];
        printf("    { name: ");
        js_str(en->name);
        printf(", pages: [");
        js_str(en->page_title[0]);
        putchar(',');
        js_str(en->page_title[1]);
        printf("],\n      edit: [");
        for (i = 0; i < 8u; i++) {
            if (i) putchar(',');
            js_desc(&en->edit[i]);
        }
        printf("],\n      presets: [");
        for (i = 0; i < en->npresets; i++) {
            if (i) putchar(',');
            js_str(en->presets[i].name);
        }
        printf("] },\n");
    }
    printf("  ],\n  track: [");
    for (i = 0; i < P_E0; i++) {
        if (i) putchar(',');
        printf("\n    ");
        js_desc(&TP[i]);
    }
    printf("],\n  global: [");
    for (i = 0; i < G_COUNT; i++) {
        if (i) putchar(',');
        printf("\n    ");
        js_desc(&GP[i]);
    }
    printf("],\n  kit: ");
    js_desc(&DRUM_KIT_DESC);
    printf(",\n};\n");
    return 0;
}
