#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""The DX7 engine's compiled-in voice bank (FELUCCA_DX7_ROM=1): build/gen/dx7_rom.h from the DX7 bulk
dumps in assets/dx7/*.syx (sorted by name; 32-voice dumps of 4104 bytes, or single-voice dumps of 163
bytes, up to 128 voices in all). Every voice is checked (7-bit bytes, a printable name, the Yamaha checksum of a dump)
and packed as in the dump: 128 bytes each.

Without FELUCCA_DX7_ROM=1 the header still exists and declares no voices, so the build never depends
on the files: the voice data in such files is rarely the builder's to redistribute, and the engine plays
the user banks in flash either way.

  tools/gen_dx7rom.py OUT.h [--dir assets/dx7]
"""
import argparse
import os
import sys
from pathlib import Path

SRC = Path(__file__).resolve().parents[1]
MAX_VOICES = 128


def check_voice(v):
    """a packed voice: 128 7-bit bytes and a printable name (as eng_dx7.c dx_voice_check: fields beyond their
    DX7 range are clamped by the engine, as a DX7 does — real dumps carry 127s); the reason it fails, or None"""
    if len(v) != 128:
        return "length"
    if any(b > 127 for b in v):
        return "8-bit data"
    if any(b < 32 for b in v[118:128]):
        return "name"
    return None


def unpack_single(d):
    """a 155-byte VCED single-voice dump -> 128-byte packed (VMEM) voice"""
    out = bytearray(128)
    for j in range(6):
        s, o = d[j * 21:(j + 1) * 21], out[j * 17:(j + 1) * 17]
        o[0:8] = s[0:8]
        o[8:11] = s[8:11]
        o[11] = s[11] | s[12] << 2
        o[12] = s[13] | s[20] << 3
        o[13] = s[14] | s[15] << 2
        o[14] = s[16]
        o[15] = s[17] | s[18] << 1
        o[16] = s[19]
        out[j * 17:(j + 1) * 17] = o
    out[102:110] = d[126:134]
    out[110] = d[134]
    out[111] = d[135] | d[136] << 3
    out[112:116] = d[137:141]
    out[116] = d[141] | d[142] << 1 | d[143] << 4
    out[117] = d[144]
    out[118:128] = d[145:155]
    return bytes(out)


def voices_of(path):
    d = path.read_bytes()
    if len(d) == 4104 and d[:6] == bytes([0xF0, 0x43, d[2], 0x09, 0x20, 0x00]) and d[-1] == 0xF7:
        if (-sum(d[6:4102])) & 0x7F != d[4102]:
            raise SystemExit(f"gen_dx7rom: {path.name}: checksum")
        return [bytes(d[6 + i * 128:6 + (i + 1) * 128]) for i in range(32)]
    if len(d) == 163 and d[:6] == bytes([0xF0, 0x43, d[2], 0x00, 0x01, 0x1B]) and d[-1] == 0xF7:
        if (-sum(d[6:161])) & 0x7F != d[161]:
            raise SystemExit(f"gen_dx7rom: {path.name}: checksum")
        return [unpack_single(d[6:161])]
    raise SystemExit(f"gen_dx7rom: {path.name}: not a DX7 32-voice (4104 B) or single-voice (163 B) dump")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("out", type=Path)
    ap.add_argument("--dir", type=Path, default=SRC / "assets" / "dx7")
    a = ap.parse_args()
    want = os.environ.get("FELUCCA_DX7_ROM") == "1"
    voices = []
    files = sorted(a.dir.glob("*.syx")) if want and a.dir.is_dir() else []
    for f in files:
        for v in voices_of(f):
            bad = check_voice(v)
            if bad:
                raise SystemExit(f"gen_dx7rom: {f.name}: voice {len(voices) + 1}: {bad}")
            voices.append(v)
    if want and not voices:
        raise SystemExit(f"gen_dx7rom: FELUCCA_DX7_ROM=1 but no .syx in {a.dir}")
    voices = voices[:MAX_VOICES]
    L = ["/* generated by tools/gen_dx7rom.py: the DX7 engine's compiled-in voices (FELUCCA_DX7_ROM) */",
         "#pragma once", "#include <stdint.h>", f"#define DX_ROM_N {len(voices)}u"]
    if voices:
        L.append(f"static const uint8_t DX_ROM[{len(voices)}][128] = {{")
        for v in voices:
            name = v[118:128].decode("latin-1")
            L.append("    /* " + name.replace("*/", "* /") + " */ {" + ", ".join(str(b) for b in v) + "},")
        L.append("};")
    a.out.write_text("\n".join(L) + "\n")
    print(f"dx7 rom: {len(voices)} voices from {len(files)} files" if voices else "dx7 rom: none (FELUCCA_DX7_ROM unset)")


if __name__ == "__main__":
    main()
